### ISSUE TITLE
Where is this repository's source code?

### ISSUE THREAD

**Issue by zaidajani** [solomonshalom/GO-Translate#1]
Hey Solomon,

As I love contributing to different repositories, I need their source code, but I cannot source code in this repo. Kindly upload the source code to the repository to make this project open source.

**Comment by solomonshalom** [comment]
Hey Zaid,

I will do it as soon as possible. I will publish the code, it is just that I am working on another project which is why I didn't upload the code yet.

**Comment by zaidajani** [comment]
Alright,

I will be waiting for the source code, Thanks.
